version: '3'
services:
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
  redis:
    container_name: redis-backend
    image: "redis:alpine"
  
  dev-web:
    environment:
        - TAG 
    container_name: dev-webapp-frontend:${TAG}
    build: .
    ports:
      - "5000:8000"
  dev-redis:
    container_name: dev-redis-backend
    image: "redis:alpine"       